### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by okoala** [okoala/fis3-vue#1]
近期的roadmap: 

- [] Server Render (isomorphic javascript)
- [] CMS (建立一个能用的内容管理系统，以取代现在简单的demo)
- [] UI Component (集成UI组件)
- [] GraphQL
- [] MongoDB (ORM)
- [] Travis 集成测试
- [] 单元测试
- [] 性能测试
- [] UI测试
- [] Docker
- [] iojs/koa

不定时会进行任务的更新~

**Comment by Comver** [comment]
持续关注。
